# Generated by Django 3.2.25 on 2025-06-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_firmware'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='firmware_folder',
            field=models.FileField(blank=True, null=True, upload_to='firmware/folders/'),
        ),
        migrations.AlterUniqueTogether(
            name='firmware',
            unique_together={('version',)},
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='device',
        ),
    ]
