# Generated by Django 3.2.25 on 2025-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20250614_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_type', 'device_id')},
        ),
    ]
