# Generated by Django 3.2.25 on 2025-06-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20250615_1131'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('device_id',), name='unique_device_id'),
        ),
    ]
