# Generated by Django 3.2.25 on 2025-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_device_unique_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(help_text='Device ID must be alphanumeric (e.g., "001", "ESP123")', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(help_text='Type of device (e.g., "BMF", "ESP")', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('device_type', 'device_id'), name='unique_device_type_id'),
        ),
    ]
